travis:
  secure:
    BINSTAR_TOKEN: AGMrWdZWhBxHMtreYHASTaNUTe92p26/BBL0xoubhn0LBx0nXWtPsilAK2tnzNkKTn/OTE6sQnfIQ717ZXH2xfj1qNx73n51ZUM36im+Wil9NEHQmb9iWrmytffOZLBHzSEUDISuzByPXss8nq5tA0YWn4d3hcK3nhZyFQU/FaI6OnXnKqe+LoFENrnql+nIy2jNhJJNZMccnYXLgUMI0QAgcMt1nTkxqFel35xcD7qRtvPlMtuHftPR07mY1ykOCet3JNv6niTW1r8qOor0+Jkjmbg/M2XV1L/pcyrt7qGpTGeuWska/RfgnGOmReyYBADhS9E5sBM1OHgE/a8RQE9n9tC/ax1gg/RG3Q/PxZJv0Hm3IxGdm3vPqUVf6KeYGqUGLW/0jWpWuJ28MN71FxiToM1GSEBRS8gtBHdT2EmbCj5He6/ozpzASUXIOTUhKqYkBUoaTrRUJ9LXG3hJ2mMZyGtSVuznkp3D75QB0WZUMdxYQMH3EFnTCrRnYuTdqr7730EcTfZMn++Ff1aqykyueRceG36OtB0Vfs0thdbrKQ+UJe+279dBYlLzwJxNS6xyDGIKUVX+s3DrRUIFgDhIijJIvXusbSjxCQFM4RhLf6txHf+8DRPZivvYfNpp2Ev30z+YCWq8sRc+a5/95T9ZVzrjFZd0Ls2Y05eAOgw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
